import { useEffect, useMemo, useState } from "react";
import { discontinuedCodesRepo, equivalencesRepo, presentationRulesRepo, productsRepo, suppliersRepo } from "@/lib/db";
import type { DiscontinuedCode, Equivalence, PresentationRule, Product, Supplier } from "@/types/database";

export default function EquivalencesPage(){
 const [tab,setTab]=useState<"rules"|"equiv">("rules"); const [suppliers,setSuppliers]=useState<Supplier[]>([]); const [rules,setRules]=useState<PresentationRule[]>([]); const [rows,setRows]=useState<(Equivalence&{product?:Product})[]>([]); const [disc,setDisc]=useState<DiscontinuedCode[]>([]); const [supplierId,setSupplierId]=useState(""); const [search,setSearch]=useState(""); const [showAdd,setShowAdd]=useState(false);
 async function load(){const ss=await suppliersRepo.list();setSuppliers(ss);setSupplierId(x=>x||ss[0]?.id||""); const [rr,ee,dd,pp]=await Promise.all([supplierId?presentationRulesRepo.listForSupplier(supplierId):Promise.resolve([]),equivalencesRepo.listConfirmed(),discontinuedCodesRepo.listForSupplier(supplierId),productsRepo.list()]); setRules(rr);const byId=new Map(pp.map(p=>[p.id,p]));setRows(ee.filter(e=>e.supplier_id===supplierId).map(e=>({...e,product:byId.get(e.product_id)})));setDisc(dd)}
 useEffect(()=>{load()},[supplierId]); useEffect(()=>{suppliersRepo.list().then(ss=>{setSuppliers(ss);if(!supplierId&&ss[0])setSupplierId(ss[0].id)})},[]);
 const filteredRules=useMemo(()=>rules.filter(r=>!search||`${r.supplier_label} ${r.own_label} ${r.supplier_pattern??""}`.toLowerCase().includes(search.toLowerCase())),[rules,search]);
 async function removeRule(id:string){if(confirm("¿Eliminar esta regla?")){await presentationRulesRepo.remove(id);load()}}
 async function removeEquiv(id:string){if(confirm("¿Eliminar esta equivalencia?")){await equivalencesRepo.remove(id);load()}}
 return <div className="mx-auto max-w-5xl"><p className="eyebrow">Memoria del sistema</p><div className="mb-5 flex items-end justify-between gap-3"><div><h1 className="font-display text-2xl font-semibold text-ink">Diccionario</h1><p className="mt-1 text-sm text-steel-600">CompraCore aprende cómo llama y presenta los productos cada proveedor.</p></div>{tab==="rules"&&<button onClick={()=>setShowAdd(true)} className="rounded bg-teal-500 px-4 py-2 text-sm font-semibold text-white">+ Nueva regla</button>}</div>
 <div className="mb-4 flex gap-1 rounded bg-steel-100 p-1 w-fit"><button onClick={()=>setTab("rules")} className={`rounded px-3 py-1.5 text-sm ${tab==="rules"?"bg-white font-semibold text-ink":"text-steel-600"}`}>Presentaciones</button><button onClick={()=>setTab("equiv")} className={`rounded px-3 py-1.5 text-sm ${tab==="equiv"?"bg-white font-semibold text-ink":"text-steel-600"}`}>Equivalencias</button></div>
 <div className="mb-4 flex gap-2"><select value={supplierId} onChange={e=>setSupplierId(e.target.value)} className="rounded border border-steel-200 bg-white px-3 py-2 text-sm"><option value="">Proveedor</option>{suppliers.filter(s=>!s.deleted_at).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar regla..." className="w-full max-w-sm rounded border border-steel-200 px-3 py-2 text-sm"/></div>
 {tab==="rules"?<div className="panel overflow-hidden"><table className="w-full text-sm"><thead className="bg-steel-50 text-left text-xs text-steel-600"><tr><th className="px-4 py-2">Proveedor</th><th className="px-4 py-2">Yo vendo</th><th className="px-4 py-2">Factor</th><th className="px-4 py-2">Ejemplo proveedor</th><th/></tr></thead><tbody className="divide-y divide-steel-100">{filteredRules.map(r=><tr key={r.id}><td className="px-4 py-3">{r.supplier_label}</td><td className="px-4 py-3 font-medium">{r.own_label}</td><td className="mono-num px-4 py-3">× {r.factor}</td><td className="px-4 py-3 text-steel-600">{r.supplier_pattern||"—"}</td><td className="px-4 py-3 text-right"><button onClick={()=>removeRule(r.id)} className="text-xs text-danger-500">Eliminar</button></td></tr>)}</tbody></table>{filteredRules.length===0&&<p className="p-8 text-center text-sm text-steel-500">Todavía no hay reglas para este proveedor.</p>}</div>
 :<div className="panel overflow-hidden"><table className="w-full text-sm"><thead className="bg-steel-50 text-left text-xs text-steel-600"><tr><th className="px-4 py-2">Código proveedor</th><th className="px-4 py-2">Mi producto</th><th className="px-4 py-2">Origen</th><th/></tr></thead><tbody className="divide-y divide-steel-100">{rows.filter(r=>!search||`${r.supplier_code} ${r.product?.code??""} ${r.product?.description??""}`.toLowerCase().includes(search.toLowerCase())).map(r=><tr key={r.id}><td className="mono-num px-4 py-3">{r.supplier_code}</td><td className="px-4 py-3">{r.product?.code} — {r.product?.description}</td><td className="px-4 py-3 text-xs text-steel-500">{r.origin}</td><td className="px-4 py-3 text-right"><button onClick={()=>removeEquiv(r.id)} className="text-xs text-danger-500">Eliminar</button></td></tr>)}</tbody></table></div>}
 {disc.length>0&&<p className="mt-4 text-xs text-steel-500">{disc.length} código(s) de este proveedor marcados como discontinuados. Se mantienen para no volver a preguntarte.</p>}
 {showAdd&&<RuleEditor suppliers={suppliers} supplierId={supplierId} onClose={()=>setShowAdd(false)} onSaved={()=>{setShowAdd(false);load()}}/>}
 </div>
}
function RuleEditor({suppliers,supplierId,onClose,onSaved}:{suppliers:Supplier[];supplierId:string;onClose:()=>void;onSaved:()=>void}){const [sid,setSid]=useState(supplierId);const [supplierLabel,setSupplierLabel]=useState("");const [ownLabel,setOwnLabel]=useState("");const [factor,setFactor]=useState(1);const [pattern,setPattern]=useState("");const [saving,setSaving]=useState(false);useEffect(()=>{setSupplierLabel(suppliers.find(s=>s.id===sid)?.name??"")},[sid,suppliers]);async function save(){if(!sid||!ownLabel.trim()||factor<=0)return;setSaving(true);await presentationRulesRepo.create({supplier_id:sid,supplier_label:supplierLabel,own_label:ownLabel.trim(),factor,supplier_pattern:pattern.trim(),own_pattern:"",active:true});setSaving(false);onSaved()}return <div className="fixed inset-0 z-50 flex items-center justify-center bg-ink/25 p-4" onClick={onClose}><div onClick={e=>e.stopPropagation()} className="panel w-full max-w-md p-6"><p className="eyebrow">Enseñar al diccionario</p><h2 className="font-display text-xl font-semibold text-ink">Nueva regla de presentación</h2><p className="mt-1 text-xs text-steel-500">Ejemplo: el proveedor vende X200 y vos lo manejás como XU.</p><div className="mt-5 space-y-3"><label className="block text-xs font-semibold">Proveedor<select value={sid} onChange={e=>setSid(e.target.value)} className="mt-1 w-full rounded border border-steel-200 px-3 py-2 text-sm">{suppliers.filter(s=>!s.deleted_at).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="block text-xs font-semibold">Presentación que usás<input value={ownLabel} onChange={e=>setOwnLabel(e.target.value)} placeholder="XU" className="mt-1 w-full rounded border border-steel-200 px-3 py-2 text-sm"/></label><label className="block text-xs font-semibold">Presentación del proveedor<input value={pattern} onChange={e=>setPattern(e.target.value)} placeholder="X200" className="mt-1 w-full rounded border border-steel-200 px-3 py-2 text-sm"/></label><label className="block text-xs font-semibold">Factor de conversión<input type="number" min="0.0001" step="0.01" value={factor} onChange={e=>setFactor(Number(e.target.value))} className="mt-1 w-full rounded border border-steel-200 px-3 py-2 text-sm"/></label></div><div className="mt-6 flex justify-end gap-2"><button onClick={onClose} className="rounded px-4 py-2 text-sm text-steel-600">Cancelar</button><button disabled={saving} onClick={save} className="rounded bg-teal-500 px-4 py-2 text-sm font-semibold text-white">Guardar regla</button></div></div></div>}
